### ISSUE TITLE
Base Null Pointer Exception

### ISSUE THREAD

**Issue by Lizzyhara** [yannickkirschen/mini-java#14]
Error:
java.lang.NullPointerException: Cannot invoke "de.dhbw.compiler.typecheck.BaseExpressionChecker.check(de.dhbw.compiler.ast.expressions.Expression)" because "this.expressionChecker" is null
(TypeCheckerTest StatementExpressionCheckerTest vgl. StatementExpressioncheck0 for example)
There is a Problem in my Code  but I cant seem to find it.

**Comment by MalteRichert** [comment]
@Lizzyhara when do you get this exception?

**Comment by yannickkirschen** [comment]
Isn't that the one we talked about yesterday, @Lizzyhara ? I though this is null because it doesn't get initialized in the test ...

**Comment by Lizzyhara** [comment]
I inizilized it after I thought some errors went away but not all, and I thought I initialized  it. 
 baseExpressionChecker = new ExpressionChecker("statementChecker",fields,localOrFieldVars,statementExpressionChecker);

**Comment by Lizzyhara** [comment]
but yeah pretty sure I failed to inizilized something I just dont see it.

**Comment by Lizzyhara** [comment]
I get this error trying to run @Test in testing_" typecheck StatementExpressionCheckerTester for example StatementExpressioncheck1


> @Lizzyhara when do you get this exception?

**Comment by Rex2002** [comment]
I think you need to call `statementExpressionChecker.setExpressionChecker(...);`  in the setup method (but the ... needs to be a `BaseExpressionChecker` and I am not quite sure where to get one)

**Comment by nichtLehdev** [comment]
> I think you need to call `statementExpressionChecker.setExpressionChecker(...);` in the setup method (but the ... needs to be a `BaseExpressionChecker` and I am not quite sure where to get one)

arent we doing that in MethodChecker luin 26 and 29?

**Comment by Rex2002** [comment]
yes, but that part of the code is not executed when running the StatementExpressionCheck1

**Comment by MalteRichert** [comment]
```
    @Test
    void  generateTypeTest0(){
        MinijavaParser.TypeContext typeContext = new MinijavaParser.TypeContext(new ParserRuleContext(),0);
        assertEquals(0,generateType(typeContext));
    }
```
produces RuntimeException because the context doesn't have any children. @Lizzyhara should we remove those tests or are you still working on them?

**Comment by Lizzyhara** [comment]
well that problem still persist so our tests simply will fail
