### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by Lizzyhara** [yannickkirschen/mini-java#15]
The Problem is more like not knowing and failing to do it right. 
MinijavaParser.MethContext methContext = new MinijavaParser.MethContext()
For the usage in methods. 
Tried to do a Path with parents, with new Programm(ArrayList(){new Method()}) and just plain nothing.

But nothing is working.

Just opend it if one of you have time you might wanna try it out too or you have a right idea

**Comment by Lizzyhara** [comment]
So, basicllly it is possible to start the methods but right now everything is null then. For Example assertEquals(,generateType(typeContext)); will be NUll (typeContext.Int() needs to be != null)

**Comment by Lizzyhara** [comment]
is there a way to add a terminalNode (Terminal Node is an interface but I dont finde where it is used)

**Comment by Rex2002** [comment]
I dont think so, the TerminalNode comes from the deep inner workings of ANTRL, 
I am not sure what you want, but if you want to have terminalNodes as inputs somewhere, maybe its better to just test the parser as a whole (basically from string-input-code to ast and not from handwritten-antrl-output to AST)

**Comment by MalteRichert** [comment]
@Lizzyhara I agree with @Rex2002 , creating the ANTLR parseTree by hand is not worth the effort. It should be enough to tests with java code as input and the AST object structure as output.

**Comment by MalteRichert** [comment]
@Lizzyhara I agree with @Rex2002 , creating the ANTLR parseTree by hand is not worth the effort. It should be enough to tests with java code as input and the AST object structure as output.

**Comment by MalteRichert** [comment]
```
@Test
    void  generateTypeTest0(){
        MinijavaParser.TypeContext typeContext = new MinijavaParser.TypeContext(new ParserRuleContext(),0);
        assertEquals(0,generateType(typeContext));
    }
```
produces RuntimeException because the context doesn't have any children. @Lizzyhara should we remove those tests or are you still working on them?
